package me.nand.npu.gui;

import static java.lang.Integer.min;
import java.text.ParseException;
import java.time.MonthDay;
import java.time.YearMonth;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import me.nand.npu.Constants;
import me.nand.npu.core.Platform;
import me.nand.npu.core.Unlocker;
import me.nand.npu.core.UnlockerException;
import me.nand.npu.core.UnlockerFactory;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class MainWindow extends javax.swing.JFrame {

    private static final long serialVersionUID = -2293914212320495384L;
    private static Logger LOGGER = LogManager.getLogger(MainWindow.class.getName());

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
		lblVersion.setText(lblVersion.getText() + Constants.VERSION);
		initWiiPanel();
	}

	private void initWiiPanel() {
		try {
			// Wii
			MaskFormatter maskFormatter = new MaskFormatter("########"); // 8 digits
			DefaultFormatterFactory formatterFactory = new DefaultFormatterFactory();
			formatterFactory.setDefaultFormatter(maskFormatter);
			jtfWiiConfNumber.setFormatterFactory(formatterFactory);
		} catch (ParseException e) {
			LOGGER.error("Error while init Wii JPanel", e);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgMessage = new javax.swing.JDialog();
        lblMessage = new javax.swing.JLabel();
        lblPlatform = new javax.swing.JLabel();
        cbxPlatform = new javax.swing.JComboBox<>();
        lblVersion = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlWii = new javax.swing.JPanel();
        jtfWiiConfNumber = new javax.swing.JFormattedTextField();
        lblWiiConfNumber = new javax.swing.JLabel();
        cbxWiiDay = new javax.swing.JComboBox<>();
        lblWiiDate = new javax.swing.JLabel();
        btnWiiCalculate = new javax.swing.JButton();
        cbxWiiMonth = new javax.swing.JComboBox<>();
        lblWiiHeader1 = new javax.swing.JLabel();
        lblWiiSteps = new javax.swing.JLabel();
        lblWiiHeader2 = new javax.swing.JLabel();
        btnWiiHelp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        dlgMessage.setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        dlgMessage.setName("dlgMessage"); // NOI18N
        dlgMessage.setUndecorated(true);
        dlgMessage.setResizable(false);
        dlgMessage.setType(java.awt.Window.Type.POPUP);

        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dlgMessageLayout = new javax.swing.GroupLayout(dlgMessage.getContentPane());
        dlgMessage.getContentPane().setLayout(dlgMessageLayout);
        dlgMessageLayout.setHorizontalGroup(
            dlgMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgMessageLayout.setVerticalGroup(
            dlgMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nintendo Parental Unlocker");
        setResizable(false);

        lblPlatform.setText("Platform:");

        cbxPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nintendo Wii" }));

        lblVersion.setText("ver ");

        pnlWii.setBorder(javax.swing.BorderFactory.createTitledBorder("Follow the steps below"));

        jtfWiiConfNumber.setColumns(8);

        lblWiiConfNumber.setText("Confirmation number:");

        cbxWiiDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lblWiiDate.setText("Date:");

        btnWiiCalculate.setText("Calculate");
        btnWiiCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWiiCalculateActionPerformed(evt);
            }
        });

        cbxWiiMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cbxWiiMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxWiiMonthActionPerformed(evt);
            }
        });

        lblWiiHeader1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWiiHeader1.setText("1- What to do:");

        lblWiiSteps.setText("<html>1.Navigate to the Wii menu by pressing the Home button on a Wii Remote.<br>2.Look at the date and time and ensure they are correct.<br>3.Select the Wii Options icon i the lower-left corner of the Wii Channel Menu.<br>4.Select \"Wii Settings\" and click on the blue arrow to reach the second settings menu.<br>5.Select \"Parental Controls\", then \"Yes\".<br>6.Select \"I forgot\", then \"I forgot\" too.");

        lblWiiHeader2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWiiHeader2.setText("2 - Get your parental control PIN");

        btnWiiHelp.setText("Help");

        javax.swing.GroupLayout pnlWiiLayout = new javax.swing.GroupLayout(pnlWii);
        pnlWii.setLayout(pnlWiiLayout);
        pnlWiiLayout.setHorizontalGroup(
            pnlWiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWiiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWiiLayout.createSequentialGroup()
                        .addComponent(lblWiiDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxWiiDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxWiiMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWiiCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWiiHelp))
                    .addGroup(pnlWiiLayout.createSequentialGroup()
                        .addGroup(pnlWiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWiiHeader1)
                            .addComponent(lblWiiSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWiiHeader2)
                            .addGroup(pnlWiiLayout.createSequentialGroup()
                                .addComponent(lblWiiConfNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfWiiConfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlWiiLayout.setVerticalGroup(
            pnlWiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWiiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWiiHeader1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWiiSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWiiHeader2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlWiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWiiConfNumber)
                    .addComponent(jtfWiiConfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlWiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWiiDate)
                    .addComponent(cbxWiiDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxWiiMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWiiCalculate)
                    .addComponent(btnWiiHelp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(pnlWii, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlWii, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlWii, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pnlWii.getAccessibleContext().setAccessibleName("");

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlatform)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVersion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlatform)
                    .addComponent(cbxPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWiiCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWiiCalculateActionPerformed
		try {
			String confirmNumber = jtfWiiConfNumber.getText();
			MonthDay monthDay = MonthDay.of(cbxWiiMonth.getSelectedIndex() + 1, cbxWiiDay.getSelectedIndex() + 1);
			Unlocker unlocker = UnlockerFactory.createUnlocker(Platform.NintendoWii, confirmNumber, monthDay);
			showMessageDialog("Your PIN code is " + unlocker.getPin(), "PIN Code");
		} catch (UnlockerException e) {
			showErrorDialog(e.getMessage(), "An error was ocurred");
		}
    }//GEN-LAST:event_btnWiiCalculateActionPerformed

    private void cbxWiiMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxWiiMonthActionPerformed
		int month = cbxWiiMonth.getSelectedIndex() + 1;
		int daysOnMonth = YearMonth.of(2000, month).lengthOfMonth();
		int daySelected = cbxWiiDay.getSelectedIndex();

		cbxWiiDay.removeAllItems();
		IntStream.range(1, daysOnMonth + 1).forEach(n -> cbxWiiDay.addItem(Integer.toString(n)));
		cbxWiiDay.setSelectedIndex(min(daySelected, daysOnMonth - 1));

    }//GEN-LAST:event_cbxWiiMonthActionPerformed

	private void showMessageDialog(String message, String title) {
		JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);
	}

	private void showErrorDialog(String message, String title) {
		JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.ERROR_MESSAGE);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		try {
			// Set System L&F
			UIManager.setLookAndFeel(
					UIManager.getSystemLookAndFeelClassName());
		} catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException
				| IllegalAccessException e) {
			LOGGER.error("Error while init UIManager", e);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new MainWindow().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWiiCalculate;
    private javax.swing.JButton btnWiiHelp;
    private javax.swing.JComboBox<String> cbxPlatform;
    private javax.swing.JComboBox<String> cbxWiiDay;
    private javax.swing.JComboBox<String> cbxWiiMonth;
    private javax.swing.JDialog dlgMessage;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JFormattedTextField jtfWiiConfNumber;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel lblWiiConfNumber;
    private javax.swing.JLabel lblWiiDate;
    private javax.swing.JLabel lblWiiHeader1;
    private javax.swing.JLabel lblWiiHeader2;
    private javax.swing.JLabel lblWiiSteps;
    private javax.swing.JPanel pnlWii;
    // End of variables declaration//GEN-END:variables
}
